version: '3.8'

services:
  percona:
    image: percona:ps-5.7
    container_name: percona
    hostname: percona
    command: --innodb_strict_mode=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 'MYSQLPORT:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQLROOTPASSWORD
      - MYSQL_DATABASE=MYSQLDATABASE
      - MYSQL_USER=MYSQLUSER
      - MYSQL_PASSWORD=MYSQLPASSWORD
      - TZ=Europe/Moscow
    restart: always
    networks:
      percona-network:
        ipv4_address: 10.2.26.2

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
    links:
      - "percona"
    ports:
      - 'PMAPORT:80'
    environment:
      - PMA_HOST=10.2.26.2
      - PMA_PORT=3306
      - HIDE_PHP_VERSION=true
      - TZ=Europe/Minsk
    depends_on:
      - percona
    restart: always
    networks:
      percona-network:
        ipv4_address: 10.2.26.3

networks:
  percona-network:
    name: percona-network
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.26.0/24
          gateway: 10.2.26.1