version: '3.8'

services:
  db:
    image: PACKAGE:MYSQLVERSION
    container_name: db
    hostname: db
    command: --innodb_strict_mode=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password
    ports:
      - 'MYSQLPORT:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQLROOTPASSWORD
      - MYSQL_DATABASE=MYSQLDATABASE
      - MYSQL_USER=MYSQLUSER
      - MYSQL_PASSWORD=MYSQLPASSWORD
      - TZ=Europe/Minsk
    restart: always
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      mysql-network:
        ipv4_address: DBNW

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
    links:
      - "db"
    ports:
      - 'PMAPORT:80'
    environment:
      - PMA_HOST=DBNW
      - PMA_PORT=3306
      - HIDE_PHP_VERSION=true
      - TZ=Europe/Minsk
    depends_on:
      - db
    restart: always
    volumes:
      - "pma-data:/etc/phpmyadmin"
    networks:
      mysql-network:
        ipv4_address: PMANW

volumes:
  db-data:
    name: "db-data"
  pma-data:
    name: "pma-data"

networks:
  mysql-network:
    name: mysql-network
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: CIDR
          gateway: GW