services:
  gitea:
      image: gitea/gitea:latest
      container_name: gitea
      hostname: DOMAIN
      restart: always
      environment:
        - USER_UID=1000
        - USER_GID=1000
        - GITEA__database__DB_TYPE=mysql
        - GITEA__database__HOST=CONT1:3306
        - GITEA__database__NAME=MYSQLDATABASE
        - GITEA__database__USER=MYSQLUSER
        - GITEA__database__PASSWD=MYSQLPASSWORD
      ports:
        - 'GHTTPPORT'
        - 'GSSHPORT:22'
      volumes:
        - gitea_data:/var/opt/gitlab
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      shm_size: '256m'
      links:
        - "db"
      networks:
        gitea-network:
          ipv4_address: CONT1
      depends_on:
        - db
  
  db:
    image: PACKAGE:MYSQLVERSION
    container_name: db
    hostname: db
    command: --innodb_strict_mode=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password
    ports:
      - 'MYSQLPORT:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQLROOTPASSWORD
      - MYSQL_DATABASE=MYSQLDATABASE
      - MYSQL_USER=MYSQLUSER
      - MYSQL_PASSWORD=MYSQLPASSWORD
      - TZ=Europe/Minsk
    restart: always
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      gitea-network:
        ipv4_address: CONT2

volumes:
  gitea_data:
    name: "gitea_data"
    external: false
  db-data:
    name: "db-data"
    external: false

networks:
  gitea-network:
    name: gitea-network
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: CIDR
          gateway: GW