services:
  gitea:
      image: gitea/gitea:latest
      container_name: gitea
      hostname: DOMAIN
      restart: always
      environment:
        - USER_UID=1000
        - USER_GID=1000
      ports:
        - 'GHTTPPORT'
        - 'GHTTPSPORT'
        - 'GSSHPORT:22'
      volumes:
        - gitea_data:/var/opt/gitlab
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      shm_size: '256m'
      networks:
        gitea-network:
          ipv4_address: CONT1

volumes:
  gitea_data:
    external: false

networks:
  gitea-network:
    name: gitea-network
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: CIDR
          gateway: GW