services:
  gitea:
      image: gitea/gitea:latest
      container_name: gitea
      hostname: DOMAIN
      restart: always
      environment:
        - USER_UID=1000
        - USER_GID=1000
      ports:
        - 'GHTTPPORT'
        - 'GSSHPORT:22'
      volumes:
        - gitea_data:/var/opt/gitlab
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      shm_size: '256m'
      networks:
        gitea-network:
          ipv4_address: CONT1
  
  db:
    image: PACKAGE:MYSQLVERSION
    container_name: db
    hostname: db
    command: --innodb_strict_mode=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password
    ports:
      - 'MYSQLPORT:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQLROOTPASSWORD
      - MYSQL_DATABASE=MYSQLDATABASE
      - MYSQL_USER=MYSQLUSER
      - MYSQL_PASSWORD=MYSQLPASSWORD
      - TZ=Europe/Minsk
    restart: always
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      mysql-network:
        ipv4_address: DBNW

volumes:
  gitea_data:
    external: false

networks:
  gitea-network:
    name: gitea-network
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: CIDR
          gateway: GW