version: '3.8'

services:
  PACKAGE:
    container_name: PACKAGE
    image: atlassian/PACKAGE
    volumes:
      - PACKAGE_data:/var/atlassian/application-data/jira
      - ./agent/atlassian-agent.bak:/atlassian-agent.jar:ro
    ports:
      - 'ATLPORT:8080'
    environment:
      JAVA_OPTS: '-javaagent:/atlassian-agent.jar'
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m
    networks:
      atlassian-network:
        ipv4_address: ATLNW

volumes:
  PACKAGE_data:
    external: false

networks:
  atlassian-network:
    name: atlassian-network
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: CIDR
          gateway: GW